### ISSUE TITLE
--url precedence in core install

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1286]
Steps to reproduce:

- `wp core download` in webroot (/var/www/site)
- create wp-cli.yml in the parent dir (/var/www)
- move everything into a subdir and copy index.php with modification (/var/www/site/secret)
- `wp core download`
- `wp core config --url=http://someurl`

`siteurl` and `home` options will be set to the URL specified in the YAML, not the one on the command line.

To debug: `error_log('AA[url] ' . $assoc_args['url']);`
at https://github.com/wp-cli/wp-cli/blob/master/php/commands/core.php#L480

*This has moved to [line #571](https://github.com/wp-cli/wp-cli/blob/master/php/commands/core.php#L571)

**Comment by szepeviktor** [comment]
@danielbachhuber Is there someone who is familiar enough for this bug?

**Comment by danielbachhuber** [comment]
> Is there someone for this bug who is familiar enough with wp-cli?

How do you mean? I haven't looked at it in depth, but could do so soon.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
Maybe I haven't read the docs:

> --url=<url> Pretend request came from given URL. In multisite, this argument is how the target site is specified.

So `--url` is not the home UrL nor the site URL but the request URL.

**Comment by szepeviktor** [comment]
@danielbachhuber Could you take another look at it?

**Comment by danielbachhuber** [comment]
> Could you take another look at it?

It's on my todo list, but I can't provide a specific timeline.

**Comment by danielbachhuber** [comment]
@szepeviktor I tried reproducing this today and couldn't: https://gist.github.com/danielbachhuber/fb85431d6e147c04ade1

I'm also not clear as to why you'd expect `wp core config --url=http://someurl` to set the URL in the database.

Can you clarify?

**Comment by szepeviktor** [comment]
WP-CLI must get a URL to set `home` and `siteurl`.
My problem is that when there are different URL-s in the YAML and on the command line, the one from the YAML gets precedence.

**Comment by szepeviktor** [comment]
...at least back in Jul 21 2014.

**Comment by danielbachhuber** [comment]
> My problem is that when there are different URL-s in the YAML and on the command line, the one from the YAML gets precedence.

I picked up on that in the initial report. However, I wasn't able to reproduce:

```
salty-wordpress ➜  site  cat ../wp-cli.yml
url: incorrect-domain.com
```

Can you try reproducing again? If you can't, we can just close this issue.

**Comment by szepeviktor** [comment]
Now it behaves correctly:
```yaml
url: http://wp-cli.wp
debug: true
core download:
  locale: hu_HU
core update:
  locale: hu_HU
core config:
  dbname: wpclidb
  dbuser: wp
  dbpass: wp
  dbprefix: cli_
core install:
  title: WordPress website
  admin_user: viktor
  admin_password: *
  admin_email: viktor@*
  url: http://wp-cli.wp/sb
```
Does not mix the two `url`-s.
