### ISSUE TITLE
extra-php not working

### ISSUE THREAD

**Issue by joelataylor** [wp-cli/wp-cli#1920]
Hi there, I'm kind of confused as to why my wp-cli.yml file isn't working as expected:

```yml
require: joel.php
core config:
  extra-php: |
    define( 'WP_ENV', 'development' );
```

And in my `wp-config.php` I have `var_dump(WP_ENV);` and it produces a `Not defined` error message. However, when I put the `define` in `joel.php` - the var prints and no error. What am I missing??

```
PHP binary:	/usr/local/Cellar/php56/5.6.10/bin/php
PHP version:	5.6.10
php.ini used:	/usr/local/etc/php/5.6/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	
WP-CLI project config:	/Users/joeltaylor/Sites/oamm/oamm.dev/wp-cli.yml
WP-CLI version:	0.17.1
```
