### ISSUE TITLE
Can we get wp plugin activate to return -1 when the plugin specified can't be found?

### ISSUE THREAD

**Issue by kitsunde** [wp-cli/wp-cli#2002]
I have an ansible task like so:

``` yml
- name: Activate the Mortgage Calculator plugin.
  sudo_user: www-data
  shell: wp plugin activate mortgage-calculator-plugin
    chdir={{wordpress_path}}
```

I noticed the **mortgage-calculator-plugin** wasn't installed and because the plugin wasn't in the **plugins** directory so it couldn't have activated, but it still returns 0. If it was -1 it would've stopped my provisioning with an error.

Could we make it return an error code so provisioning failures gets registered?
