### ISSUE TITLE
Commands :: Core :: Install :: wp-cli adds "/wordpress" to the end of site url

### ISSUE THREAD

**Issue by lots0logs** [wp-cli/wp-cli#2563]
### Problem
When running `core install` command, wp-cli always puts `/wordpress` at the end of the site url regardless of what you pass to it via command arguments or place in `wp-cli.yml`.

### Steps To Reproduce
1. Create `wp-cli.yml` as shown below.
2. `~/wp-cli.phar core download`
3. `~/wp-cli.phar core config`
4. `~/wp-cli.phar core install --admin_user=wpdev --admin_password=wordpressdev --admin_email=admin@somesite.com --skip-email --title=WordPress --url='http://wpdev.dev:8080'`
5.  `~/wp-cli.phar option get siteurl` shows that siteurl has `/wordpress` tacked on the end of it.

##### `~/wp-cli.yml`:
```yml
path: /home/ubuntu/wordpress
url: 'http://wpdev.dev:8080'
user: wpdev
debug: true
allow-root: true
core config:
  dbhost: localhost
  dbname: wordpress
  dbuser: ubuntu
  dbpass: 
  extra-php: |
    define( 'WP_DEBUG', true );
    define( 'WP_DEBUG_LOG', true );
    define( 'WP_SITEURL', 'http://wpdev.dev:8080' );
    define( 'WP_HOMEURL', 'http://wpdev.dev:8080' );
```
##### Server Environment:
* Ubuntu 12.04
* PHP 5.5.2
* PostgreSQL 9.4
* Apache 2.2.22
