### ISSUE TITLE
extend "package management" functionality with aliases and pseudo manifest file

### ISSUE THREAD

**Issue by jambox** [wp-cli/wp-cli#3284]
This might be possible already and I just haven't been able to find it in the docs, but I'm imagining an array in the `wp-cli.yml` file or a separate file that could act as a package management manifest. Sometimes I'm using crappy client servers that don't have composer but have `wp` installed. It would be great to have the following setup so I could automate installing the dependencies, especially using the aliases feature:

```yaml
...
# Inside wp-cli.yml 
dependencies:
  plugins:
    - google-analyticator
    - adminimize
    - maintenance-mode
    - user-switching
    - advanced-custom-fields
    - http://s3.amazonaws.com/bucketname/my-plugin.zip?AWSAccessKeyId=123&amp;Expires=456&amp;Signature=abcdef
  themes:
    - twentysixteen
    - ./client-theme.zip
...
```
which would subsequently allow for usage like
```
$ wp @dev plugin install --dependencies
$ wp @dev theme install ---dependencies
$ wp @dev dependencies install
```

Right now the way I'm able to do this is by running:

`$ wp plugin install $(< plugins.txt)`

where `plugins.txt` looks like:
```
google-analyticator
adminimize
maintenance-mode
user-switching
advanced-custom-fields
```

which is easy enough, but I thought incoprorating into core would be helpful for other folks.

Thoughts? I know this is kind of redundant, as composer is already a robust php package management solution, but I figure if I'm moving towards management my wp installs with wp-cli, if it could also have the power to read from a manifest it'd be a great one stop shop kind of deal.

Thanks!
