### ISSUE TITLE
--allow-root is not passed on to alias groups

### ISSUE THREAD

**Issue by markjaquith** [wp-cli/wp-cli#4146]
wp-cli.yml:

```yaml
@foo:
  path: foo
@bar
  path: bar
@foobar:
  - @foo
  - @bar
```

In a docker instance which runs as root (like using Local, by Flywheel), you have to use `--allow-root`.

This works:

`wp --allow-root core version`

This works:

`wp @foo --allow-root core version`

This does **not** work:

`wp @foobar --allow-root core version`

This does **not** work:

`wp @all --allow-root core version`

The last two generate the running-as-root warning, so it does not appear that that the `--allow-root` flag is getting passed on appropriately.
