### ISSUE TITLE
Aliases in config files cannot be merged

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#4706]
Given the following config files, I would expect that both the `@one` and `@two` aliases would be available in the local environment due to the use of the `_: merge: true` setting, but this is not the case. Instead, `@two` overrides `@one`. It seems to be that aliases cannot be merged.

```yaml
# wp-cli.yml
@one:
  ssh: foo
  user: bar
```

```yaml
# wp-cli.local.yml
_:
  merge: true

@two:
  ssh: baz
  user: qux
```

**Comment by gitlost** [comment]
Yes, it only parses one of `wp-cli.local.yml`, `wp-cli.yml` in that order. You could simulate the behaviour you want by doing:
```yaml
# wp-cli.local.yml
_:
  inherit: wp-cli.yml

@two:
  ssh: baz
  user: qux
```
