### ISSUE TITLE
Creating recommended Docker image for wp-cli

### ISSUE THREAD

**Issue by dustinvanbuskirk** [wp-cli/wp-cli#4727]
I'd like to reopen the discussion on creating a Docker image for wp-cli.

I know it has been discussed and decided that this isn't something that the current contributors have time to support.

I'd like to discuss how this would look.

I work at Codefresh and can handle all the Docker CI work in Codefresh and link up to this repository to use as the source code.  This means we do not have to add a Dockerfile into the repository to support the Docker build we can do this from Codefresh and push out to Docker Hub which allows for free storage of Docker images.

A few questions for the contributors here to help me get started.

Question 1 - Can we create a WP-CLI organization in Docker Hub?  I would prefer a contributor to this repository do that and add me.  That way it is still under some control by contributors here and it is easier to find by folks.

Question 2 - Is anyone interested in helping me maintain the image build in Codefresh?  I have built a separate wp-cli account in Codefresh and can add additional collaborators. 

Question 3 - Sort of an additional to Question 1.  How will we point users to the recommended but unsupported Docker image?

This is just a starter discussion so feel free to set some clear acceptance criteria from your side for this to be something feasible.  The driver behind this on my side is I am going to be using this Docker image with a customer who wants to not be using something created by another user not known to them and not in any way affiliated with wp-cli.  I am not sure how this affiliation would work see Question 3.

**Comment by dustinvanbuskirk** [comment]
Pipeline YAML
```
version: '1.0'
steps:
  BuildingDockerImage:
    title: Building Docker Image
    type: build
    image_name: dustinvanbuskirk/wp-cli
    working_directory: ./
    dockerfile:
      content: >-
        FROM php:7-alpine


        MAINTAINER Dustin Van Buskirk


        ENV VERSION=${{CF_BRANCH}}


        RUN docker-php-ext-install mysqli


        RUN curl -Lo /bin/wp
        https://github.com/wp-cli/wp-cli/releases/download/${VERSION}/wp-cli-${VERSION//v}.phar
        && \
            chmod +x /bin/wp
            
        ENTRYPOINT /bin/wp


        CMD wp --info
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
  RunningUnitTests:
    title: Running Unit Tests
    image: '${{BuildingDockerImage}}'
    working_directory: IMAGE_WORK_DIR
    entry_point:
      - /bin/sh
      - /codefresh/volume/cf-generated/unit_test_script
    create_file:
      path: /codefresh/volume/cf-generated
      name: unit_test_script
      content: wp --info
    on_success:
      metadata:
        set:
          - '${{BuildingDockerImage.imageId}}':
              - CF_QUALITY: true
    on_fail:
      metadata:
        set:
          - '${{BuildingDockerImage.imageId}}':
              - CF_QUALITY: false
  PushingToDockerRegistry:
    title: Pushing to Docker Registry
    type: push
    candidate: '${{BuildingDockerImage}}'
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    registry: dockerhubdvb
```

I've used my own Docker Hub repository until one is selected by contributors.
https://hub.docker.com/r/dustinvanbuskirk/wp-cli

Give this is utilizing a tag like `v1.5.0` I used Codefresh CLI to execute the build, this can be done as part of a release process if someone would like.
Command: `codefresh run 5aa6cd5fff6d7500019a4b2e -b v1.5.0`
You can detach from the process as well and let it finish on its own outside your CI.

Badge for README specific to v1.5.0 [![Codefresh build status]( https://g.codefresh.io/api/badges/build?repoOwner=wp-cli&repoName=wp-cli&branch=v1.5.0&pipelineName=wp-cli&accountName=wp-cli&type=cf-1)]( https://g.codefresh.io/repositories/wp-cli/wp-cli/builds?filter=trigger:build;branch:v1.5.0;service:5aa6cd5fff6d7500019a4b2e~wp-cli)
You cannot visit this link without a Codefresh user but we can set those up.  We're also working currently to enable settings to expose this similar to your TravisCI for open source projects like this.
