### ISSUE TITLE
Pin wordpress version in .wpcli.yaml

### ISSUE THREAD

**Issue by skhaz** [wp-cli/wp-cli#5647]
Is there some way to pin the WordPress version using `.wpcli.yaml`?

I tried 

```yaml
core:
  version: 5.9.3
```
or

```yaml
core install:
  version: 5.9.3
core update:
  version: 5.9.3
```

But no luck, it always download the latest version

**Comment by wojsmol** [comment]
@skhaz I tested this `wp-cli.yml` without `.` at a beginning of the filename with WP-CLI 2.6.0 AND IT'WORKING:
```YML
core download:
    version: 5.9.3
core update:
    version: 5.9.3
```
