### ISSUE TITLE
Pin WordPress version

### ISSUE THREAD

**Issue by skhaz** [wp-cli/wp-cli#5648]
I am using `WP_CLI_CONFIG_PATH` with this YAML

```yaml
core download:
  version: 5.9.3
core install:
  version: 5.9.3
core update:
  version: 5.9.3
```

And I could pin the WordPress version to 5.9.3. However, on our production site, I noticed sometimes the WordPress gets updated and I do not know what command is being called.

I thought that only `core download` and `core update` is used to upgrade the version.

Are there other ways to upgrade the WordPress that I am missing?
