### ISSUE TITLE
Windows Powershell configuration

### ISSUE THREAD

**Issue by timotheemoulin** [wp-cli/wp-cli#5677]
The `wp-cli` command configuration has some mismatches with Windows Powershell.

e.g. the `ALIAS_REGEX` constant used to configure remote instances because it uses the `@` symbol as a prefix.
`@` is used (like the `$` character as a variable prefix) to expand the variable (converts a string variable in an array).

https://github.com/wp-cli/wp-cli/blob/b179c7a096b5de51a002f91a7a9ad1e0183678b5/php/WP_CLI/Configurator.php#L47

Would that be possible to allow overriding the constant with some filter?

Alternative question, why are we using `@prod` structure to define the aliases in the `wp-cli.yml` instead of an array of values like `disabled_commands` or `require`?

**Comment by timotheemoulin** [comment]
Hi @danielbachhuber,

The `@` seems linked to Powershell. I never encountered this issue with GitBash. So I don't really know if we can figure out the character to use based on the operating system.


Regarding the syntax, here is a small `wp-cli.yml` example file from [the doc](https://make.wordpress.org/cli/handbook/references/config/).

```yml
path: wp-core
url: http://example.com
user: admin
color: false
disabled_commands:
  - db drop
  - plugin install
require:
  - path-to/command.php

@staging:
    ssh: wpcli@staging.wp-cli.org
    user: wpcli
    path: /srv/www/staging.wp-cli.org
```

My question is why do we configure `@staging` alias as a root node value instead of something like:

```yml
aliases:
  staging:
    ssh: wpcli@staging.wp-cli.org
    user: wpcli
    path: /srv/www/staging.wp-cli.org    
```
That way, we could have an easy way to define aliases without a fancy regexp.
