### ISSUE TITLE
Having wp-cli.yml and wp-cli.local.yml in the same directory not working

### ISSUE THREAD

**Issue by marcinkrzeminski** [wp-cli/wp-cli#5784]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

I'd like to be able to have my local settings inside the `wp-cli.local.yml` (ignored with `.gitignore`) and the ones that I'd like to share with the team via `wp-cli.yml`. However when I have both of these in the same directory the `wp-cli.local.yml` is serving the purpose.

Example `wp-cli.yml`:

```yml
path: wp/
disabled_commands:
  - db drop
  - db reset
  - plugin delete
```

Example `wp-cli.local.yml`

```yml
@prod:
  ssh: user@example.com
  path: /srv/www/example.com

@dev:
  ssh: user@dev.example.com
  path: /srv/www/dev.example.com

@all:
  - @prod
  - @dev
```

It would be great if I could have these in the same location.
