### ISSUE TITLE
inherit: not inheriting disabled_commands

### ISSUE THREAD

**Issue by kkmuffme** [wp-cli/wp-cli#6023]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

disabled_commands are not inherited

wp-cli.yml

```
# some comment
disabled_commands:
    - eval-file
    - cache

# '_' is a special value denoting configuration options for this wp-cli.yml
_:
    merge: true
    # Inherit configuration from an arbitrary YAML file
    inherit: prod.yml
```

prod.yml

```
disabled_commands:
    - eval
```

>wp cli has-command "eval"; echo "$?"
>0
>wp cli has-command "eval-file"; echo "$?"
>1

**Describe what you expect as the correct outcome**

I'd expect 1 in both cases
Using `merge: true` makes no difference

**Let us know what environment you are running this on**

```
OS:     Linux 5.14.0-162.23.1.el9_1.x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php
PHP version:    7.4.33
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /foo
WP-CLI packages dir:    /bar/.wp-cli/packages/
WP-CLI cache dir:       /bar/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:  /foo/wp-cli.yml
WP-CLI version: 2.11.0
```
